services:
  nginx:
    container_name: container-nginx
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./.docker/nginx/conf:/etc/nginx/conf.d
      - ./.docker/nginx/cert:/etc/ssl/certs
      - ./dist/client:/usr/share/nginx/html

  backend:
    container_name: container-backend
    build:
      context: .
      dockerfile: bun.Dockerfile
    ports:
      - 3000:3000
